[package]
name = "rectangle"
version = "0.1.0"
authors = ["m0t0k1ch1 <m0t0k1ch1.310@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
